### ISSUE TITLE
[controller] modify criteria to filter out non-mp3 formats

### ISSUE THREAD

**Issue by rabdulwahhab** [rayyan3/random-soundcloud#8]
Server can generate error if calling `download` with sc-dl and that track doesnt have an associated mp3:

`Error: Could not find media with specified format: (audio/mpeg)
    at /Users/rayyan/www/random-soundcloud/node_modules/soundcloud-downloader/dist/index.js:93:27
    at step (/Users/rayyan/www/random-soundcloud/node_modules/soundcloud-downloader/dist/index.js:52:23)
    at Object.next (/Users/rayyan/www/random-soundcloud/node_modules/soundcloud-downloader/dist/index.js:33:53)
    at fulfilled (/Users/rayyan/www/random-soundcloud/node_modules/soundcloud-downloader/dist/index.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by rabdulwahhab** [comment]
Abrogated -- by way of the sc embed
